# Generated by Django 5.1.4 on 2025-01-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titl_tag',
            field=models.CharField(default='WordCanvas', max_length=255),
        ),
    ]
