# Generated by Django 5.1.4 on 2025-01-09 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0003_rename_titl_tag_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
